# Change these first
owner: datanomi # Your GitHub organization or username, where this repository lives
repo: mha.fi-statuspage # The name of this repository

sites:
  - name: Homepage
    url: https://mha.fi
  - name: Mail Server
    url: https://hautaluoma.eu
  - name: SearX
    url: https://searx.mha.fi
  - name: Invidious
    url: https://tube.mha.fi
  - name: Teddit
    url: https://teddit.mha.fi
  - name: Nitter
    url: https://nitter.it
  - name: Bin
    url: https://bin.mha.fi
  - name: Link Shortener
    url: https://7m.ee
  - name: Bibliogram
    url: https://gram.mha.fi

status-website:
  cname: status.mha.fi
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://mha.fi/content/favicon.png
  name: mha.fi Status page
  introMessage: Status page for all my different things.
  navbar:
    - title: Home
      href: https://mha.fi
      
      
  NOTIFICATION_DISCORD: true,
  NOTIFICATION_DISCORD_WEBHOOK: true,
  NOTIFICATION_DISCORD_WEBHOOK_URL: ${{ secrets.DC_WEBHOOK }}
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
